apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fitu
spec:
  selector:
    app: fitu-mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  clusterIP: None
