apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: fitu
  labels:
    app: fitu-chat
spec:
  selector:
    app: fitu-chat
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  type: ClusterIP
